### ISSUE TITLE
Using macros for the symbol in nomencl Package

### ISSUE THREAD

**Issue by eldroiderino** [mgeier/homepage#16]
Hi,

I am generating a nomenclature using the nomencl package in conjunction with latexmk. My problem is that i cannot use a macro for defining the symbol. E.g. the following commands

```
\newcommand\dpart{$d_\mathrm{p}$}
\nomenclature[adpa]{\dpart}{particle diameter}
```

result in this error message of latexmk:

```
! Undefined control sequence.
<argument> \dpart 
                  
l.4   \item [{\dpart}]
                      \begingroup particle diameter\nomeqref {0.0}\nompagere...

? ^C
! Emergency stop.
<argument> \dpart 
                  
l.4   \item [{\dpart}]
                      \begingroup particle diameter\nomeqref {0.0}\nompagere...

!  ==> Fatal error occurred, no output PDF file produced!
```

Directly compiling the document with pdflatex works. Any help would be greatly appreciated.

**Comment by mgeier** [comment]
I'm not sure if I can help, but I can try to look into it if you provide a minimal reproducible example.

You can also try to ask at https://tex.stackexchange.com/, but I guess they'll also ask for an MRE.

**Comment by mgeier** [comment]
Closing due to lack of response.
