### ISSUE TITLE
Can you import local modules without sys.path and symbolic link ?

### ISSUE THREAD

**Issue by bouachalazhar** [mgeier/homepage#20]
I would like to import modules in subfolder from folder/modules/module.py in my notebook from folder/notebooks/example.ipynb without sys.path and symbolic link because I will use it in several notebooks and many times.

**Comment by mgeier** [comment]
As I mention in https://mg.readthedocs.io/importing-local-python-modules-from-jupyter-notebooks/index.html:

> If you re-use local modules a lot, you should consider turning them into proper Python packages which can be installed with Python’s package manager `pip`.

Local imports are sometimes quick and easy, but you shouldn't over-use them.

**Comment by bouachalazhar** [comment]
> As I mention in https://mg.readthedocs.io/importing-local-python-modules-from-jupyter-notebooks/index.html:
> 
> 
> 
> > If you re-use local modules a lot, you should consider turning them into proper Python packages which can be installed with Python’s package manager `pip`.
> 
> 
> 
> Local imports are sometimes quick and easy, but you shouldn't over-use them.

How can I transform local package to Python package but unfortunately I couldn't do it. I try to create an empty setup.py file in project and empty __init__.py file for each module. For example:

- project
    - Notebooks
        - example.ipynb
    - modules
        - module1
            - new.py

**Comment by mgeier** [comment]
> How can I transform local package to Python package

Did you try typing that into a search engine?

**Comment by bouachalazhar** [comment]
> > How can I transform local package to Python package
> 
> 
> 
> Did you try typing that into a search engine?

Yes, but when I add it in Pythonpath it doesn't work. I just would like to know if can I use my local repo and update it on GitLab with the same architecture above.

**Comment by mgeier** [comment]
Yes, you can.
