### ISSUE TITLE
Latexmkrc

### ISSUE THREAD

**Issue by atmafox** [mgeier/homepage#3]
Hey, sorry to open an issue here but I couldn't find other ways to contact you.

I'm working on a project with latexmk and having trouble getting success_cmd to function.  It's being parsed, but it doesn't seem to be running the command I put into it; specifically a gs command to generate a compressed PDF after the main PDF is generated.  Feel free to close this issue if it's inappropriate, but if possible where should I contact for assistance with this?

**Comment by mgeier** [comment]
Don't worry, it's OK to ask questions here!

Can you please tell me how you were using `success_cmd` (or a simplified version of your usage)?

**Comment by mgeier** [comment]
Closing due to lack of response.
